# Site settings
title: union.io
header-img: img/home-bg.png
email: ian@union.io
description: "union.io â€” Tech, design, and typographic anger"
baseurl: ""
url: "http://blog.union.io"
twitter_username: union_io
github_username:  i-a-n
facebook_username:  65MYA

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","deploy.sh"]
